/**
 * Hello World from Claude
 * Generated by Claude (claude-sonnet-4-6) via Claude Code
 */
public class HelloClaude {
    public static void main(String[] args) {
        System.out.println("Hello, World! 👋");
        System.out.println("This program was written by Claude, Anthropic's AI assistant.");
        System.out.println("Running on Java " + System.getProperty("java.version"));
    }
}
